name: Build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:

  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        node-version: [16, 18, 20, 22]
        npm_package_manager: [yarn, pnpm, npm]
        os: [
            macos-13,
            macos-15,
            ubuntu-24.04,
            ubuntu-24.04-arm,
            windows-latest
          ]
    name: Test ${{ matrix.os }}-${{ matrix.node-version }}-${{ matrix.npm_package_manager }}

    env:
      NODE_VERSION: ${{ matrix.node-version }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: ${{ matrix.npm_package_manager }}

      - run: ${{ matrix.npm_package_manager }} install --save-dev @you54f/pact jest axios
      - run: ${{ matrix.npm_package_manager }} run test

